In [36]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', None)

In [2]:
tn_trends_by_ss = pd.read_excel("../data/AEPSi_Data.xlsx")

In [3]:
tn_trends_by_ss.head()

,Summary Statement 1,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,...,2011-12.1,2012-13.1,2013-14.1,2014-15.1,2015-16.1,2016-17.1,2017-18.1,2018-19.1,2019-20.1,2020-21.1
0,TN Positive Social-Emotional Skills,0.739,0.767,0.751,0.848,0.7099,0.746,0.7415,0.6841,0.5686,...,0.425,0.3413,0.418,0.3566,0.4393,0.4954,0.4823,0.4815,0.4473,0.4583
1,TN Acquisition and Use of Knowledge and Skills,0.774,0.748,0.773,0.862,0.7462,0.787,0.7461,0.7201,0.5601,...,0.421,0.3546,0.398,0.2962,0.2911,0.3193,0.3155,0.3244,0.2970,0.3303
2,TN Appropriate Behaviors to Meet Needs,0.759,0.769,0.793,0.890,0.7744,0.805,0.7870,0.7631,0.6532,...,0.403,0.3468,0.376,0.3126,0.3740,0.5120,0.5605,0.5828,0.5578,0.5727
3,National Positive Social-Emotional Skills,0.630,0.660,0.650,0.650,0.6500,0.650,0.6600,0.6500,0.6600,...,0.600,0.5900,0.590,0.5900,0.5900,0.5800,0.5700,0.5600,0.5400,NaN
4,National Acquisition and Use of Knowledge and ...,0.680,0.690,0.700,0.700,0.7000,0.710,0.7100,0.7100,0.7200,...,0.510,0.5000,0.510,0.5000,0.5000,0.4800,0.4800,0.4700,0.4500,NaN

In [4]:
aeps_to_eco_crosswalk = pd.read_excel('../data/AEPSi_Data.xlsx', 1)
aeps_to_eco_crosswalk.head()

,Outcome 2: Acquisition and use of knowledge and skills,Unnamed: 1,Unnamed: 2
0,Domain,Item,AEPS Item
1,Fine motor,• Orients picture book correctly and turns pag...,fm_B4.0
2,Fine motor,• Copies simple written shapes after demonstra...,fm_B5.0
3,Cognitive,• Imitates words not frequently used,cog_D2.0
4,Cognitive,• Uses an object to obtain another object,cog_E2.0

In [5]:
aeps_2017_2022 = pd.read_excel('../data/AEPSi_Data.xlsx', 2)
aeps_2017_2022.head()

,Child ID,Program Name,AEPSi ID,AssessID,State,Child First,Child Last,DOB,Gender,Dev Status,...,Adapt Result,Cog Goal Score,Cog Cutoff,Cog Result,SC Goal Score,SC Cutoff,SC Result,Soc Goal Score,Soc Cutoff,Soc Result
0,11,Signal Centers,722747,10584304,TN,XXXXXX,XXXXXX,2020-02-02 00:00:00,M,Dev. Delay or Disability,...,above,17.0,20.0,below,11.0,13.0,below,9.0,9.0,below
1,10724,Little Tennessee Valley Educational Cooperative,707878,10575064,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,3.0,4.0,below,2.0,3.0,below,0.0,1.0,below
2,10724,Little Tennessee Valley Educational Cooperative,707878,10589703,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,5.0,4.0,above,3.0,3.0,below,2.0,1.0,above
3,11112,SRVS,665041,10535282,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,8.0,7.5,above,7.0,5.0,above,7.0,4.0,above
4,11112,SRVS,665041,10503223,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,5.0,4.0,above,5.0,3.0,above,5.0,1.0,above

In [15]:
aeps_2017_2022['cog_G1.0'].value_counts(normalize=True)

0.0    0.926551
1.0    0.053848
2.0    0.019601
Name: cog_G1.0, dtype: float64

In [16]:
aeps_2017_2022['cog_G2.0'].value_counts(normalize=True)

0.0    0.945707
1.0    0.036418
2.0    0.017875
Name: cog_G2.0, dtype: float64

In [17]:
aeps_2017_2022['cog_G3.0'].value_counts(normalize=True)

0.0    0.882893
1.0    0.081468
2.0    0.035639
Name: cog_G3.0, dtype: float64

In [18]:
aeps_2017_2022['cog_G4.0'].value_counts(normalize=True)

0.0    0.905892
1.0    0.069384
2.0    0.024724
Name: cog_G4.0, dtype: float64

In [19]:
aeps_2017_2022['cog_G5.0'].value_counts(normalize=True)

0.0    0.932342
1.0    0.040428
2.0    0.027230
Name: cog_G5.0, dtype: float64

In [20]:
aeps_2017_2022['cog_G6.0'].value_counts(normalize=True)

0.0    0.941029
1.0    0.040149
2.0    0.018822
Name: cog_G6.0, dtype: float64

In [35]:
aeps_2017_2022

,Child ID,Program Name,AEPSi ID,AssessID,State,Child First,Child Last,DOB,Gender,Dev Status,...,Adapt Result,Cog Goal Score,Cog Cutoff,Cog Result,SC Goal Score,SC Cutoff,SC Result,Soc Goal Score,Soc Cutoff,Soc Result
0,11,Signal Centers,722747,10584304,TN,XXXXXX,XXXXXX,2020-02-02 00:00:00,M,Dev. Delay or Disability,...,above,17.0,20.0,below,11.0,13.0,below,9.0,9.0,below
1,10724,Little Tennessee Valley Educational Cooperative,707878,10575064,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,3.0,4.0,below,2.0,3.0,below,0.0,1.0,below
2,10724,Little Tennessee Valley Educational Cooperative,707878,10589703,TN,XXXXXX,XXXXXX,2021-07-30 00:00:00,F,Dev. Delay or Disability,...,above,5.0,4.0,above,3.0,3.0,below,2.0,1.0,above
3,11112,SRVS,665041,10535282,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,8.0,7.5,above,7.0,5.0,above,7.0,4.0,above
4,11112,SRVS,665041,10503223,TN,XXXXXX,XXXXXX,2020-04-27 00:00:00,F,Dev. Delay or Disability,...,below,5.0,4.0,above,5.0,3.0,above,5.0,1.0,above
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17954,NaN,Porter Leath,528914,10224622,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,1.0,4.0,below,1.0,3.0,below,1.0,1.0,below
17955,NaN,Porter Leath,528913,10222226,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,0.0,1.0,below,2.0,0.0,above,0.0,0.0,below
17956,NaN,Porter Leath,528913,10224623,TN,XXXXXX,XXXXXX,2016-05-04 00:00:00,F,Dev. Delay or Disability,...,below,0.0,4.0,below,3.0,3.0,below,2.0,1.0,above
17957,NaN,Porter Leath,532226,10231183,TN,XXXXXX,XXXXXX,########,M,Dev. Delay or Disability,...,below,0.0,7.5,below,3.0,5.0,below,0.0,4.0,below
17958,NaN,Porter Leath,532787,10232713,TN,XXXXXX,XXXXXX,########,M,Dev. Delay or Disability,...,below,14.0,29.0,below,7.0,15.5,below,7.0,10.0,below

In [26]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G1.0'])

cog_G1.0    0.0  1.0  2.0
Gender
2             0    0    1
F          6604  325  124
M         10035  642  227

In [27]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G2.0'])

cog_G2.0    0.0  1.0  2.0
Gender
2             0    0    1
F          6671  257  125
M         10312  397  195

In [28]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G3.0'])

cog_G3.0   0.0  1.0  2.0
Gender
2            0    0    1
F         6303  515  235
M         9552  948  404

In [29]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G4.0'])

cog_G4.0   0.0  1.0  2.0
Gender
2            0    0    1
F         6416  471  166
M         9852  775  277

In [30]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G5.0'])

cog_G5.0    0.0  1.0  2.0
Gender
2             0    0    1
F          6594  273  186
M         10149  453  302

In [31]:
pd.crosstab(aeps_2017_2022['Gender'], aeps_2017_2022['cog_G6.0'])

cog_G6.0    0.0  1.0  2.0
Gender
2             0    0    1
F          6604  308  141
M         10295  413  196

In [37]:
aeps = pd.read_excel("../data/AEPSi_Data.xlsx", 2, usecols=["Child ID", "Program Name", "AEPSi ID", "AssessID", "State", "DOB", "Gender", "Dev Status", "AEPS Level", "Test Date", "Examiner", "Service Coordinator", "TEIS Point of Entry Office (POE)", "ESL", "County of Residence", "Number of Items", "fm_B4.0", "fm_B5.0", "cog_D2.0", "cog_E2.0", "cog_E4.0", "cog_F1.0", "cog_G1.0", "cog_G2.0", "cog_G3.0", "cog_G4.0", "cog_G5.0", "cog_G6.0", "sc_B1.0", "sc_B2.0", "sc_D1.0", "sc_D2.0", "sc_D3.0", "FM Raw Score", "FM Possible Score", "FM Percentage", "Cog Raw Score", "Cog Possible Score", "Cog Percentage", "SC Raw Score", "SC Possible Score", "SC Percentage"])
aeps.head()

,Child ID,Program Name,AEPSi ID,AssessID,State,DOB,Gender,Dev Status,AEPS Level,Test Date,Examiner,Service Coordinator,TEIS Point of Entry Office (POE),ESL,County of Residence,Number of Items,fm_B4.0,fm_B5.0,cog_D2.0,cog_E2.0,cog_E4.0,cog_F1.0,cog_G1.0,cog_G2.0,cog_G3.0,cog_G4.0,cog_G5.0,cog_G6.0,sc_B1.0,sc_B2.0,sc_D1.0,sc_D2.0,sc_D3.0,FM Raw Score,FM Possible Score,FM Percentage,Cog Raw Score,Cog Possible Score,Cog Percentage,SC Raw Score,SC Possible Score,SC Percentage
0,11,Signal Centers,722747,10584304,TN,2020-02-02 00:00:00,M,Dev. Delay or Disability,1,2022-04-21 00:00:00,Maria E. Vives-Rodriguez,Mary Crowder,Southeast Tennessee,N,Hamilton,249.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,2.0,1.0,0.0,0.0,51.0,66.0,0.7727,65.0,116.0,0.5603,52.0,92.0,0.5652
1,10724,Little Tennessee Valley Educational Cooperative,707878,10575064,TN,2021-07-30 00:00:00,F,Dev. Delay or Disability,1,2022-03-01 00:00:00,Olivia J Woodall;Olivia Woodall,Charity Decker,East Tennessee,N,Blount,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,66.0,0.2879,26.0,116.0,0.2241,15.0,92.0,0.163
2,10724,Little Tennessee Valley Educational Cooperative,707878,10589703,TN,2021-07-30 00:00:00,F,Dev. Delay or Disability,1,2022-05-09 00:00:00,Olivia J Woodall;Olivia Woodall,Charity Decker,East Tennessee,N,Blount,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,66.0,0.4394,41.0,116.0,0.3534,24.0,92.0,0.2609
3,11112,SRVS,665041,10535282,TN,2020-04-27 00:00:00,F,Dev. Delay or Disability,1,2021-07-08 00:00:00,Beth Murphree,Michael Brasher,Memphis/Delta Tennessee,N,Shelby,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,41.0,66.0,0.6212,36.0,116.0,0.3103,28.0,92.0,0.3043
4,11112,SRVS,665041,10503223,TN,2020-04-27 00:00:00,F,Dev. Delay or Disability,1,2020-12-30 00:00:00,Beth Murphree,Michael Brasher,Memphis/Delta Tennessee,N,Shelby,249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,33.0,66.0,0.5000,18.0,116.0,0.1552,18.0,92.0,0.1957

In [34]:
aeps.corr()

,AEPSi ID,AEPS Level,Number of Items,fm_B4.0,fm_B5.0,cog_D2.0,cog_E2.0,cog_E4.0,cog_F1.0,cog_G1.0,...,sc_D1.0,sc_D2.0,sc_D3.0,FM Raw Score,FM Possible Score,FM Percentage,Cog Raw Score,Cog Possible Score,SC Raw Score,SC Possible Score
AEPSi ID,1.000000,-0.199192,0.190414,0.100209,0.021037,0.008600,0.118180,0.116200,0.046949,0.049352,...,0.036228,-0.026471,-0.037531,0.168405,-0.199203,0.170553,0.131899,0.199203,0.057995,0.199203
AEPS Level,-0.199192,1.000000,-0.965395,0.021666,0.059317,0.022781,0.014777,0.016651,0.027271,0.040478,...,0.019784,0.034860,0.050306,0.023004,1.000000,0.012394,-0.008248,-1.000000,-0.003562,-1.000000
Number of Items,0.190414,-0.965395,1.000000,-0.021985,-0.056264,-0.021862,-0.012829,-0.015110,-0.025596,-0.038810,...,-0.021923,-0.032484,-0.047559,-0.021916,-0.965395,-0.011673,0.007007,0.965395,0.001803,0.965395
fm_B4.0,0.100209,0.021666,-0.021985,1.000000,0.372298,0.444727,0.476991,0.547825,0.493482,0.411836,...,0.357614,0.381888,0.301178,0.573637,0.021666,0.573507,0.562768,-0.021666,0.517695,-0.021666
fm_B5.0,0.021037,0.059317,-0.056264,0.372298,1.000000,0.286322,0.265673,0.295084,0.340953,0.316894,...,0.191473,0.256872,0.225857,0.278000,0.059317,0.277417,0.294497,-0.059317,0.280855,-0.059317
cog_D2.0,0.008600,0.022781,-0.021862,0.444727,0.286322,1.000000,0.477381,0.498668,0.437553,0.344648,...,0.527170,0.626757,0.505295,0.485174,0.022781,0.485019,0.619151,-0.022781,0.676391,-0.022781
cog_E2.0,0.118180,0.014777,-0.012829,0.476991,0.265673,0.477381,1.000000,0.658517,0.412806,0.361869,...,0.456483,0.398132,0.299291,0.607755,0.014777,0.607710,0.689109,-0.014777,0.602395,-0.014777
cog_E4.0,0.116200,0.016651,-0.015110,0.547825,0.295084,0.498668,0.658517,1.000000,0.493778,0.408359,...,0.459846,0.427110,0.331694,0.622240,0.016651,0.622177,0.702814,-0.016651,0.627665,-0.016651
cog_F1.0,0.046949,0.027271,-0.025596,0.493482,0.340953,0.437553,0.412806,0.493778,1.000000,0.388369,...,0.320984,0.412664,0.337324,0.423719,0.027271,0.423503,0.499282,-0.027271,0.483595,-0.027271
cog_G1.0,0.049352,0.040478,-0.038810,0.411836,0.316894,0.344648,0.361869,0.408359,0.388369,1.000000,...,0.271824,0.361517,0.327875,0.340354,0.040478,0.339982,0.426038,-0.040478,0.390018,-0.040478
cog_G2.0,0.021484,0.044890,-0.042380,0.376558,0.321352,0.359031,0.321349,0.355262,0.389420,0.468244,...,0.276836,0.385289,0.359160,0.299167,0.044890,0.298740,0.395981,-0.044890,0.389503,-0.044890
cog_G3.0,0.042236,0.030771,-0.029317,0.410354,0.292734,0.494568,0.417787,0.453374,0.437736,0.420666,...,0.402703,0.518549,0.437802,0.402488,0.030771,0.402231,0.518566,-0.030771,0.533236,-0.030771
cog_G4.0,0.043443,0.035754,-0.033833,0.463490,0.319388,0.402975,0.351269,0.426341,0.440968,0.438690,...,0.294895,0.390856,0.345526,0.352158,0.035754,0.351839,0.438979,-0.035754,0.421595,-0.035754
cog_G5.0,0.006246,0.037949,-0.036553,0.359551,0.269102,0.419637,0.356982,0.393738,0.378785,0.414962,...,0.351742,0.451454,0.419963,0.327487,0.037949,0.327138,0.451346,-0.037949,0.462871,-0.037949
cog_G6.0,-0.016444,0.043372,-0.041066,0.347316,0.297599,0.473253,0.306352,0.343602,0.357657,0.343391,...,0.356141,0.524001,0.530104,0.292406,0.043372,0.291995,0.400279,-0.043372,0.449614,-0.043372
sc_B1.0,0.100274,0.012521,-0.014642,0.507533,0.252099,0.542894,0.569417,0.616814,0.443848,0.346157,...,0.551016,0.462774,0.329430,0.673801,0.012521,0.673793,0.733903,-0.012521,0.766846,-0.012521
sc_B2.0,0.037534,0.014079,-0.012320,0.420965,0.224573,0.623103,0.506041,0.522506,0.400389,0.292346,...,0.641931,0.530608,0.379891,0.615921,0.014079,0.615887,0.709580,-0.014079,0.790055,-0.014079
sc_D1.0,0.036228,0.019784,-0.021923,0.357614,0.191473,0.527170,0.456483,0.459846,0.320984,0.271824,...,1.000000,0.534276,0.429979,0.641384,0.019784,0.641296,0.714589,-0.019784,0.784958,-0.019784
sc_D2.0,-0.026471,0.034860,-0.032484,0.381888,0.256872,0.626757,0.398132,0.427110,0.412664,0.361517,...,0.534276,1.000000,0.735144,0.399919,0.034860,0.399619,0.528937,-0.034860,0.680491,-0.034860
sc_D3.0,-0.037531,0.050306,-0.047559,0.301178,0.225857,0.505295,0.299291,0.331694,0.337324,0.327875,...,0.429979,0.735144,1.000000,0.287343,0.050306,0.286857,0.401114,-0.050306,0.545214,-0.050306
FM Raw Score,0.168405,0.023004,-0.021916,0.573637,0.278000,0.485174,0.607755,0.622240,0.423719,0.340354,...,0.641384,0.399919,0.287343,1.000000,0.023004,0.999944,0.915843,-0.023004,0.814077,-0.023004
FM Possible Score,-0.199203,1.000000,-0.965395,0.021666,0.059317,0.022781,0.014777,0.016651,0.027271,0.040478,...,0.019784,0.034860,0.050306,0.023004,1.000000,0.012394,-0.008248,-1.000000,-0.003562,-1.000000
FM Percentage,0.170553,0.012394,-0.011673,0.573507,0.277417,0.485019,0.607710,0.622177,0.423503,0.339982,...,0.641296,0.399619,0.286857,0.999944,0.012394,1.000000,0.916101,-0.012394,0.814265,-0.012394
Cog Raw Score,0.131899,-0.008248,0.007007,0.562768,0.294497,0.619151,0.689109,0.702814,0.499282,0.426038,...,0.714589,0.528937,0.401114,0.915843,-0.008248,0.916101,1.000000,0.008248,0.911095,0.008248
Cog Possible Score,0.199203,-1.000000,0.965395,-0.021666,-0.059317,-0.022781,-0.014777,-0.016651,-0.027271,-0.040478,...,-0.019784,-0.034860,-0.050306,-0.023004,-1.000000,-0.012394,0.008248,1.000000,0.003562,1.000000
SC Raw Score,0.057995,-0.003562,0.001803,0.517695,0.280855,0.676391,0.602395,0.627665,0.483595,0.390018,...,0.784958,0.680491,0.545214,0.814077,-0.003562,0.814265,0.911095,0.003562,1.000000,0.003562
SC Possible Score,0.199203,-1.000000,0.965395,-0.021666,-0.059317,-0.022781,-0.014777,-0.016651,-0.027271,-0.040478,...,-0.019784,-0.034860,-0.050306,-0.023004,-1.000000,-0.012394,0.008248,1.000000,0.003562,1.000000